### ISSUE TITLE
EXE file triggers Windows Defender

### ISSUE THREAD

**Issue by ByteLabDev** [GuilhermeTorq/steascii#2]
Detects it as Trojan:Win32/Wacatac.B!ml

![image](https://github.com/GuilhermeTorq/steascii/assets/67926878/ddd4488c-8fe0-498f-b9a8-00beb6bf6d01)

**Comment by 8041q** [comment]
Unfortunately, by using pyinstaller windows acts like that
It's a executable which has been modified to act as a python interpreter, so it's unique to not be anywhere else, doesn't have a signature and windows doesn't like that.

But you can just download the code file (steascii.py) and run it with python.

I'm looking for a way to make python executables fine
